name: NormieProgression
main: io.github._13shoot.normieprogression.NormieProgression
version: 0.4.0
api-version: 1.21
author: 13shoot

softdepend:
  - PlaceholderAPI

commands:
  np:
    description: Normie Progression command
    usage: /np
